<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Career;
use Illuminate\Support\Str;

class CareerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $careers = [
            [
                'title_vi' => 'Chuyên viên Kinh doanh Bất động sản',
                'title_en' => 'Real Estate Sales Associates',
                'slug' => 'real-estate-sales-associates',
                'location_vi' => 'Hà Nội, Việt Nam',
                'location_en' => 'Hanoi, Vietnam',
                'job_type' => 'full-time',
                'experience_required' => '4+ Years',
                'salary_display' => '50K',
                'salary_min' => 30000000,
                'salary_max' => 50000000,
                'salary_currency' => 'VND',
                'salary_period' => 'monthly',
                'image' => '/frontend/assets/img/career/single-career.jpg',
                'description_vi' => 'Tại Renius Real Estate & Construction Group, chúng tôi tin vào việc xây dựng không chỉ là tài sản mà còn là sự nghiệp có mục đích. Cho dù bạn là một kỹ sư dày dạn kinh nghiệm, một kiến trúc sư đầy tham vọng, hay một chuyên gia bất động sản năng động, Renius cung cấp một nền tảng để phát triển, lãnh đạo và đổi mới.',
                'description_en' => 'At Renius Real Estate & Construction Group, we believe in building more than just properties—we build careers with purpose. Whether you\'re a seasoned engineer, an aspiring architect, or a driven real estate professional, Renius offers a platform for growth, leadership, and innovation.',
                'responsibilities_vi' => [
                    'Hỗ trợ khách hàng trong việc mua, bán hoặc thuê bất động sản',
                    'Thực hiện đánh giá tài sản và nghiên cứu thị trường',
                    'Hợp tác với các thành viên trong nhóm để đạt được mục tiêu kinh doanh',
                    'Đảm bảo tuân thủ các tiêu chuẩn ngành và yêu cầu pháp lý',
                    'Duy trì mối quan hệ khách hàng tốt và giải đáp thắc mắc kịp thời',
                ],
                'responsibilities_en' => [
                    'Assist clients in buying, selling, or renting properties',
                    'Conduct property evaluations and market research',
                    'Collaborate with other team members to achieve sales goals',
                    'Ensure compliance with industry standards and legal requirements',
                    'Maintain strong client relationships and address inquiries promptly',
                ],
                'qualifications_vi' => [
                    'Bằng Cử nhân hoặc kinh nghiệm tương đương',
                    'Kinh nghiệm 4 năm trở lên',
                    'Kỹ năng giao tiếp, đàm phán và dịch vụ khách hàng tốt',
                    'Thành thạo các công cụ/phần mềm cụ thể nếu cần',
                    'Hiểu biết về các tiêu chuẩn hoặc quy định đặc thù của ngành',
                ],
                'qualifications_en' => [
                    'Bachelor\'s degree or equivalent experience',
                    '4+ years of experience',
                    'Strong skills in communication, negotiation, customer service',
                    'Proficiency in specific tools/software, if needed',
                    'Knowledge of industry-specific standards or regulations',
                ],
                'benefits_vi' => [
                    'Mức lương và cơ cấu thưởng cạnh tranh',
                    'Cơ hội phát triển và thăng tiến nghề nghiệp',
                    'Chế độ sức khỏe và phúc lợi toàn diện',
                    'Môi trường làm việc linh hoạt',
                    'Văn hóa công ty hỗ trợ và hòa nhập',
                ],
                'benefits_en' => [
                    'Competitive salary and bonus structure',
                    'Opportunities for career growth and development',
                    'Comprehensive health and wellness benefits',
                    'Flexible work environment',
                    'Supportive and inclusive company culture',
                ],
                'application_deadline' => now()->addDays(30),
                'application_email' => 'careers@renius.vn',
                'application_url' => null,
                'positions_available' => 3,
                'department_vi' => 'Phòng Kinh doanh',
                'department_en' => 'Sales Department',
                'order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Trưởng phòng Marketing',
                'title_en' => 'Marketing Manager',
                'slug' => 'marketing-manager',
                'location_vi' => 'Hồ Chí Minh, Việt Nam',
                'location_en' => 'Ho Chi Minh, Vietnam',
                'job_type' => 'full-time',
                'experience_required' => '3+ Years',
                'salary_display' => '40K - 60K',
                'salary_min' => 40000000,
                'salary_max' => 60000000,
                'salary_currency' => 'VND',
                'salary_period' => 'monthly',
                'image' => '/frontend/assets/img/career/single-career.jpg',
                'description_vi' => 'Chúng tôi đang tìm kiếm một Trưởng phòng Marketing có kinh nghiệm để lãnh đạo các chiến dịch marketing và xây dựng thương hiệu cho công ty. Vị trí này yêu cầu tư duy chiến lược, kỹ năng lãnh đạo xuất sắc và kinh nghiệm trong lĩnh vực bất động sản.',
                'description_en' => 'We are seeking an experienced Marketing Manager to lead marketing campaigns and brand building for the company. This position requires strategic thinking, excellent leadership skills, and experience in the real estate industry.',
                'responsibilities_vi' => [
                    'Phát triển và thực hiện chiến lược marketing tổng thể',
                    'Quản lý ngân sách marketing và đo lường ROI',
                    'Lãnh đạo và phát triển đội ngũ marketing',
                    'Xây dựng và duy trì hình ảnh thương hiệu công ty',
                    'Phân tích thị trường và đối thủ cạnh tranh',
                    'Phối hợp với các phòng ban khác để đạt mục tiêu kinh doanh',
                ],
                'responsibilities_en' => [
                    'Develop and implement overall marketing strategy',
                    'Manage marketing budget and measure ROI',
                    'Lead and develop marketing team',
                    'Build and maintain company brand image',
                    'Analyze market and competitors',
                    'Coordinate with other departments to achieve business goals',
                ],
                'qualifications_vi' => [
                    'Bằng Cử nhân chuyên ngành Marketing hoặc liên quan',
                    'Tối thiểu 3 năm kinh nghiệm ở vị trí tương đương',
                    'Kinh nghiệm trong lĩnh vực bất động sản là một lợi thế',
                    'Kỹ năng lãnh đạo và quản lý đội nhóm',
                    'Thành thạo các công cụ marketing digital',
                    'Kỹ năng phân tích dữ liệu và báo cáo',
                ],
                'qualifications_en' => [
                    'Bachelor\'s degree in Marketing or related field',
                    'Minimum 3 years of experience in similar position',
                    'Experience in real estate industry is an advantage',
                    'Leadership and team management skills',
                    'Proficiency in digital marketing tools',
                    'Data analysis and reporting skills',
                ],
                'benefits_vi' => [
                    'Lương cạnh tranh + thưởng theo hiệu suất',
                    'Bảo hiểm sức khỏe cao cấp',
                    'Thưởng cuối năm theo kết quả kinh doanh',
                    'Đào tạo và phát triển kỹ năng thường xuyên',
                    'Môi trường làm việc chuyên nghiệp và sáng tạo',
                ],
                'benefits_en' => [
                    'Competitive salary + performance bonus',
                    'Premium health insurance',
                    'Year-end bonus based on business results',
                    'Regular training and skill development',
                    'Professional and creative work environment',
                ],
                'application_deadline' => now()->addDays(45),
                'application_email' => 'hr@renius.vn',
                'application_url' => null,
                'positions_available' => 1,
                'department_vi' => 'Phòng Marketing',
                'department_en' => 'Marketing Department',
                'order' => 2,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Kỹ sư Phần mềm',
                'title_en' => 'Software Developer',
                'slug' => 'software-developer',
                'location_vi' => 'Làm việc từ xa',
                'location_en' => 'Remote',
                'job_type' => 'contract',
                'experience_required' => '5+ Years',
                'salary_display' => 'Thỏa thuận',
                'salary_min' => 50000000,
                'salary_max' => 80000000,
                'salary_currency' => 'VND',
                'salary_period' => 'monthly',
                'image' => '/frontend/assets/img/career/single-career.jpg',
                'description_vi' => 'Chúng tôi đang tìm kiếm một Kỹ sư Phần mềm có kinh nghiệm để phát triển và duy trì các hệ thống quản lý bất động sản. Đây là vị trí làm việc từ xa với lịch trình linh hoạt.',
                'description_en' => 'We are looking for an experienced Software Developer to develop and maintain real estate management systems. This is a remote position with flexible schedule.',
                'responsibilities_vi' => [
                    'Thiết kế và phát triển ứng dụng web/mobile',
                    'Viết code sạch, có thể bảo trì và có tài liệu',
                    'Tham gia code review và testing',
                    'Làm việc với team để phân tích yêu cầu',
                    'Tối ưu hóa hiệu suất ứng dụng',
                    'Cập nhật và bảo trì hệ thống hiện có',
                ],
                'responsibilities_en' => [
                    'Design and develop web/mobile applications',
                    'Write clean, maintainable and documented code',
                    'Participate in code review and testing',
                    'Work with team to analyze requirements',
                    'Optimize application performance',
                    'Update and maintain existing systems',
                ],
                'qualifications_vi' => [
                    'Bằng Cử nhân Khoa học Máy tính hoặc tương đương',
                    'Tối thiểu 5 năm kinh nghiệm lập trình',
                    'Thành thạo Laravel, PHP, MySQL',
                    'Kinh nghiệm với Vue.js hoặc React',
                    'Hiểu biết về RESTful API',
                    'Kỹ năng giải quyết vấn đề tốt',
                ],
                'qualifications_en' => [
                    'Bachelor\'s degree in Computer Science or equivalent',
                    'Minimum 5 years of programming experience',
                    'Proficiency in Laravel, PHP, MySQL',
                    'Experience with Vue.js or React',
                    'Understanding of RESTful API',
                    'Good problem-solving skills',
                ],
                'benefits_vi' => [
                    'Làm việc từ xa 100%',
                    'Lương theo năng lực và kinh nghiệm',
                    'Thưởng dự án và performance',
                    'Trang thiết bị làm việc đầy đủ',
                    'Cơ hội học hỏi công nghệ mới',
                ],
                'benefits_en' => [
                    '100% remote work',
                    'Salary based on capability and experience',
                    'Project and performance bonuses',
                    'Full work equipment provided',
                    'Opportunity to learn new technologies',
                ],
                'application_deadline' => now()->addDays(60),
                'application_email' => 'tech@renius.vn',
                'application_url' => 'https://forms.gle/example',
                'positions_available' => 2,
                'department_vi' => 'Phòng IT',
                'department_en' => 'IT Department',
                'order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Quản lý Dự án Xây dựng',
                'title_en' => 'Construction Project Manager',
                'slug' => 'construction-project-manager',
                'location_vi' => 'Đà Nẵng, Việt Nam',
                'location_en' => 'Da Nang, Vietnam',
                'job_type' => 'full-time',
                'experience_required' => '2+ Years',
                'salary_display' => '50K - 70K',
                'salary_min' => 50000000,
                'salary_max' => 70000000,
                'salary_currency' => 'VND',
                'salary_period' => 'monthly',
                'image' => '/frontend/assets/img/career/single-career.jpg',
                'description_vi' => 'Tại Renius Real Estate & Construction Group, chúng tôi đang tìm kiếm một Quản lý Dự án Xây dựng có kinh nghiệm để điều phối và giám sát các dự án xây dựng quy mô lớn.',
                'description_en' => 'At Renius Real Estate & Construction Group, we are looking for an experienced Construction Project Manager to coordinate and oversee large-scale construction projects.',
                'responsibilities_vi' => [
                    'Lập kế hoạch và giám sát tiến độ dự án',
                    'Quản lý ngân sách và nguồn lực dự án',
                    'Điều phối các bên liên quan và nhà thầu',
                    'Đảm bảo chất lượng và an toàn công trình',
                    'Báo cáo tiến độ cho ban lãnh đạo',
                ],
                'responsibilities_en' => [
                    'Plan and monitor project progress',
                    'Manage project budget and resources',
                    'Coordinate stakeholders and contractors',
                    'Ensure quality and safety of construction',
                    'Report progress to management',
                ],
                'qualifications_vi' => [
                    'Bằng Cử nhân Kỹ thuật Xây dựng hoặc liên quan',
                    'Tối thiểu 2 năm kinh nghiệm quản lý dự án',
                    'Kỹ năng lãnh đạo và quản lý đội nhóm',
                    'Hiểu biết về quy trình xây dựng và an toàn lao động',
                    'Kỹ năng giao tiếp và đàm phán tốt',
                ],
                'qualifications_en' => [
                    'Bachelor\'s degree in Civil Engineering or related field',
                    'Minimum 2 years of project management experience',
                    'Leadership and team management skills',
                    'Understanding of construction processes and safety',
                    'Good communication and negotiation skills',
                ],
                'benefits_vi' => [
                    'Lương cơ bản + thưởng dự án',
                    'Bảo hiểm đầy đủ theo quy định',
                    'Xe công tác và điện thoại',
                    'Cơ hội thăng tiến rõ ràng',
                    'Môi trường làm việc năng động',
                ],
                'benefits_en' => [
                    'Base salary + project bonus',
                    'Full insurance as per regulations',
                    'Company vehicle and phone',
                    'Clear career advancement opportunities',
                    'Dynamic work environment',
                ],
                'application_deadline' => now()->addDays(20),
                'application_email' => 'recruitment@renius.vn',
                'application_url' => null,
                'positions_available' => 2,
                'department_vi' => 'Phòng Dự án',
                'department_en' => 'Project Department',
                'order' => 4,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Thực tập sinh Marketing',
                'title_en' => 'Marketing Intern',
                'slug' => 'marketing-intern',
                'location_vi' => 'Hà Nội, Việt Nam',
                'location_en' => 'Hanoi, Vietnam',
                'job_type' => 'internship',
                'experience_required' => 'Sinh viên năm cuối',
                'salary_display' => '5-8 triệu',
                'salary_min' => 5000000,
                'salary_max' => 8000000,
                'salary_currency' => 'VND',
                'salary_period' => 'monthly',
                'image' => '/frontend/assets/img/career/single-career.jpg',
                'description_vi' => 'Cơ hội thực tập tuyệt vời cho sinh viên đam mê marketing và bất động sản. Bạn sẽ được làm việc trực tiếp với đội ngũ marketing chuyên nghiệp và tham gia vào các dự án thực tế.',
                'description_en' => 'Great internship opportunity for students passionate about marketing and real estate. You will work directly with professional marketing team and participate in real projects.',
                'responsibilities_vi' => [
                    'Hỗ trợ team marketing trong các chiến dịch',
                    'Quản lý social media và content',
                    'Nghiên cứu thị trường và đối thủ',
                    'Tham gia tổ chức sự kiện',
                    'Chuẩn bị báo cáo và tài liệu marketing',
                ],
                'responsibilities_en' => [
                    'Support marketing team in campaigns',
                    'Manage social media and content',
                    'Market and competitor research',
                    'Participate in event organization',
                    'Prepare marketing reports and materials',
                ],
                'qualifications_vi' => [
                    'Sinh viên năm 3, 4 hoặc mới tốt nghiệp',
                    'Chuyên ngành Marketing, Truyền thông hoặc liên quan',
                    'Có kiến thức cơ bản về digital marketing',
                    'Kỹ năng sử dụng Photoshop, Canva là một lợi thế',
                    'Tiếng Anh giao tiếp tốt',
                ],
                'qualifications_en' => [
                    'Junior, senior year or fresh graduate',
                    'Major in Marketing, Communications or related',
                    'Basic knowledge of digital marketing',
                    'Skills in Photoshop, Canva is an advantage',
                    'Good English communication',
                ],
                'benefits_vi' => [
                    'Trợ cấp thực tập hấp dẫn',
                    'Cơ hội học hỏi thực tế',
                    'Môi trường làm việc chuyên nghiệp',
                    'Có thể trở thành nhân viên chính thức',
                    'Giấy chứng nhận thực tập',
                ],
                'benefits_en' => [
                    'Attractive internship allowance',
                    'Practical learning opportunities',
                    'Professional work environment',
                    'Potential to become full-time employee',
                    'Internship certificate',
                ],
                'application_deadline' => now()->addDays(15),
                'application_email' => 'intern@renius.vn',
                'application_url' => null,
                'positions_available' => 3,
                'department_vi' => 'Phòng Marketing',
                'department_en' => 'Marketing Department',
                'order' => 5,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($careers as $career) {
            Career::create($career);
        }
    }
}
