<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Project;
use Carbon\Carbon;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'title_vi' => 'Tòa nhà Metasoftware',
                'title_en' => 'Metasoftware Building',
                'slug' => 'metasoftware-building',
                'project_number' => '01',
                'status' => 'completed',
                'project_type_vi' => 'Xây dựng',
                'project_type_en' => 'Building',
                'commencement_date' => Carbon::parse('2024-05-28'),
                'completion_date' => Carbon::parse('2024-12-15'),
                'main_image' => '/frontend/assets/img/project/single-project-1.jpg',
                'short_description_vi' => 'Tòa nhà thương mại và dân cư hiện đại với thiết kế tiên tiến',
                'short_description_en' => 'Modern commercial and residential building with advanced design',
                'description_vi' => '<p>Tại Renius Real Estate & Construction Group, mỗi dự án kể một câu chuyện về tầm nhìn, độ chính xác và tác động. Từ các tòa tháp cao cấp đến các trung tâm thương mại rộng lớn và phát triển cơ sở hạ tầng, danh mục đầu tư của chúng tôi phản ánh cam kết sâu sắc về chất lượng, đổi mới và sự hài lòng của khách hàng.</p><p>Mỗi công trình được lập kế hoạch cẩn thận và thực hiện chuyên nghiệp để đáp ứng các tiêu chuẩn cao nhất. Ngoài các dự án dân cư và thương mại, danh mục đầu tư của chúng tôi còn bao gồm các phát triển cộng đồng tập trung vào việc tăng cường sự gắn kết địa phương.</p>',
                'description_en' => '<p>At Renius Real Estate & Construction Group, every project tells a story of vision, precision, and impact. From luxury residential towers to expansive commercial hubs and infrastructure developments, our portfolio reflects a deep commitment to quality, innovation, and client satisfaction.</p><p>Each build is carefully planned and expertly executed to meet the highest standards. In addition to residential and commercial projects, our portfolio also includes community developments that focus on enhancing local engagement.</p>',
                'features_vi' => [
                    'Khái niệm hóa và ý tưởng',
                    'Lựa chọn vật liệu và tính bền vững',
                    'Phát triển thiết kế chi tiết',
                    'Tuân thủ quy chuẩn xây dựng và an toàn',
                    'Tính bền vững và các yếu tố môi trường',
                    'Hồ sơ xây dựng cuối cùng'
                ],
                'features_en' => [
                    'Conceptualisation And Ideation',
                    'Material Selection And Sustainability',
                    'Detailed Design Development',
                    'Building Code Compliance and Safety',
                    'Sustainability Environmental Considerations',
                    'Final Construction Documents'
                ],
                'location_vi' => 'Hà Nội, Việt Nam',
                'location_en' => 'Hanoi, Vietnam',
                'client_name' => 'Metasoftware Corporation',
                'budget' => 50000000000,
                'area' => '5000 m²',
                'order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Văn phòng Metasoftware',
                'title_en' => 'Metasoftware Office',
                'slug' => 'metasoftware-office',
                'project_number' => '02',
                'status' => 'in_progress',
                'main_image' => '/frontend/assets/img/project/project-1.jpg',
                'project_type_vi' => 'Văn phòng',
                'project_type_en' => 'Office',
                'commencement_date' => Carbon::parse('2024-08-15'),
                'short_description_vi' => 'Không gian văn phòng hiện đại với công nghệ tiên tiến',
                'short_description_en' => 'Modern office space with advanced technology',
                'description_vi' => '<p>Dự án văn phòng Metasoftware được thiết kế để tạo ra một môi trường làm việc hiện đại, năng động và sáng tạo. Với diện tích rộng rãi và ánh sáng tự nhiên, không gian này được tối ưu hóa để nâng cao năng suất và sự hợp tác.</p>',
                'description_en' => '<p>The Metasoftware Office project is designed to create a modern, dynamic and creative working environment. With spacious areas and natural light, this space is optimized to enhance productivity and collaboration.</p>',
                'features_vi' => [
                    'Thiết kế không gian mở',
                    'Hệ thống chiếu sáng thông minh',
                    'Phòng họp hiện đại',
                    'Khu vực nghỉ ngơi và giải trí'
                ],
                'features_en' => [
                    'Open space design',
                    'Smart lighting system',
                    'Modern meeting rooms',
                    'Rest and recreation areas'
                ],
                'location_vi' => 'TP. Hồ Chí Minh, Việt Nam',
                'location_en' => 'Ho Chi Minh City, Vietnam',
                'area' => '3000 m²',
                'order' => 2,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Trụ sở chính Metasoftware',
                'title_en' => 'Metasoftware Headquarters',
                'slug' => 'metasoftware-headquarters',
                'project_number' => '03',
                'status' => 'completed',
                'main_image' => '/frontend/assets/img/project/project-2.jpg',
                'project_type_vi' => 'Trụ sở chính',
                'project_type_en' => 'Headquarters',
                'commencement_date' => Carbon::parse('2024-03-01'),
                'completion_date' => Carbon::parse('2024-10-30'),
                'short_description_vi' => 'Trụ sở chính với kiến trúc độc đáo và hiện đại',
                'short_description_en' => 'Headquarters with unique and modern architecture',
                'description_vi' => '<p>Trụ sở chính Metasoftware là biểu tượng của sự đổi mới và phát triển bền vững. Với kiến trúc độc đáo, tòa nhà không chỉ là nơi làm việc mà còn là điểm đến thu hút cho khách hàng và đối tác.</p>',
                'description_en' => '<p>Metasoftware Headquarters is a symbol of innovation and sustainable development. With unique architecture, the building is not only a workplace but also an attractive destination for customers and partners.</p>',
                'features_vi' => [
                    'Kiến trúc xanh',
                    'Công nghệ tiết kiệm năng lượng',
                    'Sảnh đón tiếp sang trọng',
                    'Hệ thống an ninh thông minh'
                ],
                'features_en' => [
                    'Green architecture',
                    'Energy-saving technology',
                    'Luxury reception lobby',
                    'Smart security system'
                ],
                'location_vi' => 'Đà Nẵng, Việt Nam',
                'location_en' => 'Da Nang, Vietnam',
                'budget' => 75000000000,
                'area' => '7500 m²',
                'order' => 3,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Tòa nhà Metasoftware 2',
                'title_en' => 'Metasoftware Building 2',
                'slug' => 'metasoftware-building-2',
                'project_number' => '04',
                'status' => 'completed',
                'main_image' => '/frontend/assets/img/project/project-3.jpg',
                'project_type_vi' => 'Xây dựng',
                'project_type_en' => 'Building',
                'commencement_date' => Carbon::parse('2024-01-15'),
                'completion_date' => Carbon::parse('2024-08-20'),
                'short_description_vi' => 'Tòa nhà thương mại với vị trí đắc địa',
                'short_description_en' => 'Commercial building with prime location',
                'location_vi' => 'Hà Nội, Việt Nam',
                'location_en' => 'Hanoi, Vietnam',
                'area' => '4500 m²',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Văn phòng Metasoftware 2',
                'title_en' => 'Metasoftware Office 2',
                'slug' => 'metasoftware-office-2',
                'project_number' => '05',
                'status' => 'in_progress',
                'main_image' => '/frontend/assets/img/project/project-4.jpg',
                'project_type_vi' => 'Văn phòng',
                'project_type_en' => 'Office',
                'commencement_date' => Carbon::parse('2024-09-01'),
                'short_description_vi' => 'Không gian làm việc linh hoạt và sáng tạo',
                'short_description_en' => 'Flexible and creative workspace',
                'location_vi' => 'Hải Phòng, Việt Nam',
                'location_en' => 'Hai Phong, Vietnam',
                'area' => '2500 m²',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Trụ sở Metasoftware 2',
                'title_en' => 'Metasoftware Headquarters 2',
                'slug' => 'metasoftware-headquarters-2',
                'project_number' => '06',
                'status' => 'completed',
                'main_image' => '/frontend/assets/img/project/project-5.jpg',
                'project_type_vi' => 'Trụ sở chính',
                'project_type_en' => 'Headquarters',
                'commencement_date' => Carbon::parse('2024-02-10'),
                'completion_date' => Carbon::parse('2024-09-15'),
                'location_vi' => 'Cần Thơ, Việt Nam',
                'location_en' => 'Can Tho, Vietnam',
                'area' => '6000 m²',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Tòa nhà Metasoftware 3',
                'title_en' => 'Metasoftware Building 3',
                'slug' => 'metasoftware-building-3',
                'project_number' => '07',
                'status' => 'completed',
                'main_image' => '/frontend/assets/img/project/project-6.jpg',
                'project_type_vi' => 'Xây dựng',
                'project_type_en' => 'Building',
                'commencement_date' => Carbon::parse('2024-04-01'),
                'completion_date' => Carbon::parse('2024-11-10'),
                'location_vi' => 'Nha Trang, Việt Nam',
                'location_en' => 'Nha Trang, Vietnam',
                'area' => '5500 m²',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Văn phòng Metasoftware 3',
                'title_en' => 'Metasoftware Office 3',
                'slug' => 'metasoftware-office-3',
                'project_number' => '08',
                'status' => 'in_progress',
                'main_image' => '/frontend/assets/img/project/single-project-1.jpg',
                'project_type_vi' => 'Văn phòng',
                'project_type_en' => 'Office',
                'commencement_date' => Carbon::parse('2024-10-01'),
                'location_vi' => 'Huế, Việt Nam',
                'location_en' => 'Hue, Vietnam',
                'area' => '3200 m²',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'title_vi' => 'Trụ sở Metasoftware 3',
                'title_en' => 'Metasoftware Headquarters 3',
                'slug' => 'metasoftware-headquarters-3',
                'project_number' => '09',
                'status' => 'completed',
                'main_image' => '/frontend/assets/img/project/project-1.jpg',
                'project_type_vi' => 'Trụ sở chính',
                'project_type_en' => 'Headquarters',
                'commencement_date' => Carbon::parse('2024-05-15'),
                'completion_date' => Carbon::parse('2024-12-01'),
                'location_vi' => 'Vũng Tàu, Việt Nam',
                'location_en' => 'Vung Tau, Vietnam',
                'area' => '8000 m²',
                'order' => 9,
                'is_active' => true,
            ],
        ];

        foreach ($projects as $projectData) {
            Project::create($projectData);
        }
    }
}
